#!/usr/bin/bash

PREV_TOTAL=0
PREV_IDLE=0

while true
do

  mem="$(free | awk '/Mem/ {printf "%d/%d\n", $3 / 1024.0, $2 / 1024.0 }')"

  # Get the total CPU statistics, discarding the 'cpu ' prefix.
  CPU=($(sed -n 's/^cpu\s//p' /proc/stat))
  IDLE=${CPU[3]} # Just the idle CPU time.

  # Calculate the total CPU time.
  TOTAL=0
  for VALUE in "${CPU[@]:0:8}"; do
    TOTAL=$((TOTAL+VALUE))
  done

  # Calculate the CPU usage since we last checked.
  DIFF_IDLE=$((IDLE-PREV_IDLE))
  DIFF_TOTAL=$((TOTAL-PREV_TOTAL))
  DIFF_USAGE=$(((1000*(DIFF_TOTAL-DIFF_IDLE)/DIFF_TOTAL+5)/10))

  # Remember the total and idle CPU times for the next check.
  PREV_TOTAL="$TOTAL"
  PREV_IDLE="$IDLE"

  vol="`pamixer --get-volume-human`"

  bri="$(brightnessctl i | awk '/Current/ {print $4}' | tr -d '()')"

  bat="`cat /sys/class/power_supply/BAT0/capacity`"

  dat="$(date '+%a %d %b %H:%M')"

  xsetroot -name "$(echo -e "\x01 $DIFF_USAGE% | \x02 $mem | \x03$vol\x04 |  $bri |  $bat% | \x04$dat")"
  sleep 1
done
