#!/usr/bin/python3

from os import system
import sys

link = sys.argv[1]

if 'github' in link:
    link = link.replace('github', 'raw.githubusercontent').replace('blob/', '')
elif 'gitlab' in link:
    link = link.replace('blob', 'raw')

system(f'wget {link}')
